### ISSUE TITLE
What is the relationship between this project and lmfit?

### ISSUE THREAD

**Issue by danielballan** [jjhelmus/leastsqbound-scipy#10]
I am a contributor https://github.com/lmfit/lmfit-py project, which has related functionality. I see that @newville has some commits in here, so I'm sure you're aware.

I like the idea of a lightweight library that does bounded least-squared fitting -- lmfit has many features and APIs, and it can seem a little heavy sometimes. Should we think about rebasing parts of lmfit onto this?

**Comment by jjhelmus** [comment]
My take is that leastsqbound an lmfit share some functionality but have a different approaches to  library designed and intended audience.  leastsqbound tries to solve a single issue, having a limited-requirement, drop in replacement for scipy.optimize.leastsq that supports defining double or single sided bounds on the fitting parameters.  lmfit is a more complete solution to least squares fitting that is very user friendly thanks to named parameters and other niceties.  Both packages enforced the boundary condition using MINUIT style parameter transformations, or at least lmfit used to use these, I have not kept up with the packages development.  

It may be possible to re-use portions of one of the packages in another but I think the overlap may be minimal.  leastsqbound is only 380 lines of code and the 2/3 of that is a copy of scipy's leastsq function.  I'm open to an collaboration or joint development if there is a plan you had in mind. 

Also, should mention that @nmayorov did some GSoC work on bounded least-squares optimization in SciPy that also may be related to leastsqbound and lmfit.  The [nmayorov/bounded-lsq](https://github.com/nmayorov/bounded-lsq) repository gives some details.

**Comment by danielballan** [comment]
That sounds right to me. I will close this issue -- I'm not chomping at the bit to refactor lmfit and I agree it's not clear it would be worthwhile anyway. It's just nice to have a record of the connection on github.

**Comment by nmayorov** [comment]
Hi, actually my GSoC work is already part of scipy. If you are interested take a look at the documentaiton http://scipy.github.io/devdocs/generated/scipy.optimize.least_squares.html#scipy.optimize.least_squares

**Comment by newville** [comment]
@danielballan @jjhelmus @nmayorov Basically lmfit stole the MINUIT bounds (and especially how to remap that onto the covariance matrix and uncertainty estimates) from leastsqbounds.py.   

Using Parameters does make lmfit slightly heavier than leastsq(), but otherwise the minimize() is pretty similar.

As for the GSOC work to add a different (and probably better) bounds implementations into scipy.optimize.leastsq(), I say GREAT!  Let's include that too!

**Comment by jjhelmus** [comment]
@nmayorov That is great news.  I've very excited that a good bounded least squares has made it into SciPy, great work!  Is this had been available years ago I do not think leastsqbound would exist.  Once SciPy 0.17.0 is released I'll add a note in the readme letting users know about this feature in SciPy and recommending they use it rather than leastsqbound.
